//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hbsis.com.br/")]
    public partial class FMT_ENVIO_Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hbsis.com.br/")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hbsis.com.br/")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hbsis.com.br/")]
    public partial class DT_RET_TRANSPORTE_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_RET_TRANSPORTE_ResponseE_RETORNO e_RETORNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RET_TRANSPORTE_ResponseE_RETORNO E_RETORNO {
            get {
                return this.e_RETORNOField;
            }
            set {
                this.e_RETORNOField = value;
                this.RaisePropertyChanged("E_RETORNO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hbsis.com.br/")]
    public partial class DT_RET_TRANSPORTE_ResponseE_RETORNO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tP_MESField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TP_MES {
            get {
                return this.tP_MESField;
            }
            set {
                this.tP_MESField = value;
                this.RaisePropertyChanged("TP_MES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hbsis.com.br/")]
    public partial class DT_RET_TRANSPORTE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_RET_TRANSPORTEI_MAPA i_MAPAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RET_TRANSPORTEI_MAPA I_MAPA {
            get {
                return this.i_MAPAField;
            }
            set {
                this.i_MAPAField = value;
                this.RaisePropertyChanged("I_MAPA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hbsis.com.br/")]
    public partial class DT_RET_TRANSPORTEI_MAPA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fATURAField;
        
        private string tRANSPORTEField;
        
        private string dT_ENTREGAField;
        
        private string hR_ENTREGAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FATURA {
            get {
                return this.fATURAField;
            }
            set {
                this.fATURAField = value;
                this.RaisePropertyChanged("FATURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSPORTE {
            get {
                return this.tRANSPORTEField;
            }
            set {
                this.tRANSPORTEField = value;
                this.RaisePropertyChanged("TRANSPORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DT_ENTREGA {
            get {
                return this.dT_ENTREGAField;
            }
            set {
                this.dT_ENTREGAField = value;
                this.RaisePropertyChanged("DT_ENTREGA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HR_ENTREGA {
            get {
                return this.hR_ENTREGAField;
            }
            set {
                this.hR_ENTREGAField = value;
                this.RaisePropertyChanged("HR_ENTREGA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hbsis.com.br/", ConfigurationName="IntegracaoCutoffWebService.SI_RET_TRANSPORTE")]
    public interface SI_RET_TRANSPORTE {
        
        // CODEGEN: Generating message contract since the operation SI_RET_TRANSPORTE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.FMT_ENVIO_Fault), Action="http://sap.com/xi/WebService/soap1.1", Name="FMT_ENVIO_Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse SI_RET_TRANSPORTE(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse> SI_RET_TRANSPORTEAsync(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RET_TRANSPORTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hbsis.com.br/", Order=0)]
        public HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE MT_RET_TRANSPORTE;
        
        public SI_RET_TRANSPORTERequest() {
        }
        
        public SI_RET_TRANSPORTERequest(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE MT_RET_TRANSPORTE) {
            this.MT_RET_TRANSPORTE = MT_RET_TRANSPORTE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RET_TRANSPORTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hbsis.com.br/", Order=0)]
        public HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE_Response MT_RET_TRANSPORTE_Response;
        
        public SI_RET_TRANSPORTEResponse() {
        }
        
        public SI_RET_TRANSPORTEResponse(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE_Response MT_RET_TRANSPORTE_Response) {
            this.MT_RET_TRANSPORTE_Response = MT_RET_TRANSPORTE_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_RET_TRANSPORTEChannel : HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_RET_TRANSPORTEClient : System.ServiceModel.ClientBase<HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE>, HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE {
        
        public SI_RET_TRANSPORTEClient() {
        }
        
        public SI_RET_TRANSPORTEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_RET_TRANSPORTEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_RET_TRANSPORTEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_RET_TRANSPORTEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE.SI_RET_TRANSPORTE(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest request) {
            return base.Channel.SI_RET_TRANSPORTE(request);
        }
        
        public HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE_Response SI_RET_TRANSPORTE(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE MT_RET_TRANSPORTE) {
            HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest inValue = new HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest();
            inValue.MT_RET_TRANSPORTE = MT_RET_TRANSPORTE;
            HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse retVal = ((HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE)(this)).SI_RET_TRANSPORTE(inValue);
            return retVal.MT_RET_TRANSPORTE_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse> HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE.SI_RET_TRANSPORTEAsync(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest request) {
            return base.Channel.SI_RET_TRANSPORTEAsync(request);
        }
        
        public System.Threading.Tasks.Task<HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTEResponse> SI_RET_TRANSPORTEAsync(HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.DT_RET_TRANSPORTE MT_RET_TRANSPORTE) {
            HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest inValue = new HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTERequest();
            inValue.MT_RET_TRANSPORTE = MT_RET_TRANSPORTE;
            return ((HBSIS.MercadoLes.Integracao.SapBrf.IntegracaoCutoffWebService.SI_RET_TRANSPORTE)(this)).SI_RET_TRANSPORTEAsync(inValue);
        }
    }
}
