//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_CUSTO_ADICIONAL_FRETE_OUTService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class FM_CUSTO_ADICIONAL_FRETE
    {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class ExchangeFaultData
    {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText
        {
            get
            {
                return this.faultTextField;
            }
            set
            {
                this.faultTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl
        {
            get
            {
                return this.faultUrlField;
            }
            set
            {
                this.faultUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail
        {
            get
            {
                return this.faultDetailField;
            }
            set
            {
                this.faultDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class ExchangeLogData
    {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response
    {
        
        private string statusField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request
    {
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao integracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao Integracao
        {
            get
            {
                return this.integracaoField;
            }
            set
            {
                this.integracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao
    {
        
        private string numeroRotaField;
        
        private string[] multiTransporteField;
        
        private System.DateTime dataField;
        
        private bool dataFieldSpecified;
        
        private string placaField;
        
        private string cpfMotoristaField;
        
        private string cnpjTransportadorField;
        
        private string unidadeNegocioField;
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia[] ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumeroRota
        {
            get
            {
                return this.numeroRotaField;
            }
            set
            {
                this.numeroRotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NumeroRota", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] MultiTransporte
        {
            get
            {
                return this.multiTransporteField;
            }
            set
            {
                this.multiTransporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified
        {
            get
            {
                return this.dataFieldSpecified;
            }
            set
            {
                this.dataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CpfMotorista
        {
            get
            {
                return this.cpfMotoristaField;
            }
            set
            {
                this.cpfMotoristaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CnpjTransportador
        {
            get
            {
                return this.cnpjTransportadorField;
            }
            set
            {
                this.cnpjTransportadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UnidadeNegocio
        {
            get
            {
                return this.unidadeNegocioField;
            }
            set
            {
                this.unidadeNegocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ocorrencia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia[] Ocorrencias
        {
            get
            {
                return this.ocorrenciasField;
            }
            set
            {
                this.ocorrenciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia
    {
        
        private string codigoField;
        
        private string nomeField;
        
        private string quantidadeField;
        
        private string houveDivergenciaField;
        
        private string quantidadeDiariaPrevistaField;
        
        private string quantidadeDiariaRealizadaField;
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens itensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Quantidade
        {
            get
            {
                return this.quantidadeField;
            }
            set
            {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HouveDivergencia
        {
            get
            {
                return this.houveDivergenciaField;
            }
            set
            {
                this.houveDivergenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string QuantidadeDiariaPrevista
        {
            get
            {
                return this.quantidadeDiariaPrevistaField;
            }
            set
            {
                this.quantidadeDiariaPrevistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string QuantidadeDiariaRealizada
        {
            get
            {
                return this.quantidadeDiariaRealizadaField;
            }
            set
            {
                this.quantidadeDiariaRealizadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens Itens
        {
            get
            {
                return this.itensField;
            }
            set
            {
                this.itensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens
    {
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem[] itemField;
        
        private string[] nomeBalsaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NomeBalsa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] NomeBalsa
        {
            get
            {
                return this.nomeBalsaField;
            }
            set
            {
                this.nomeBalsaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem
    {
        
        private string codigoClienteField;
        
        private string valorDescargaPrevistoField;
        
        private string valorDescargaRealizadoField;
        
        private string motivoField;
        
        private string quantidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoCliente
        {
            get
            {
                return this.codigoClienteField;
            }
            set
            {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ValorDescargaPrevisto
        {
            get
            {
                return this.valorDescargaPrevistoField;
            }
            set
            {
                this.valorDescargaPrevistoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ValorDescargaRealizado
        {
            get
            {
                return this.valorDescargaRealizadoField;
            }
            set
            {
                this.valorDescargaRealizadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Quantidade
        {
            get
            {
                return this.quantidadeField;
            }
            set
            {
                this.quantidadeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", ConfigurationName="SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT")]
    public interface SI_CUSTO_ADICIONAL_FRETE_OUT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SI_CUSTO_ADICIONAL_FRETE_OUTService.FM_CUSTO_ADICIONAL_FRETE), Action="http://sap.com/xi/WebService/soap1.1", Name="FM_CUSTO_ADICIONAL_FRETE")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", Order=0)]
        public SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTRequest()
        {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTRequest(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request)
        {
            this.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", Order=0)]
        public SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response;
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTResponse()
        {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTResponse(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response)
        {
            this.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface SI_CUSTO_ADICIONAL_FRETE_OUTChannel : SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTClient : System.ServiceModel.ClientBase<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT>, SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_CUSTO_ADICIONAL_FRETE_OUTClient.GetBindingForEndpoint(endpointConfiguration), SI_CUSTO_ADICIONAL_FRETE_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_CUSTO_ADICIONAL_FRETE_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_CUSTO_ADICIONAL_FRETE_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT.SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request)
        {
            return base.Channel.SI_CUSTO_ADICIONAL_FRETE_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request)
        {
            SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest inValue = new SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest();
            inValue.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
            return ((SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT)(this)).SI_CUSTO_ADICIONAL_FRETE_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://spouxp2d:50200/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_" +
                        "HB_SIS&receiverParty=&receiverService=&interface=SI_CUSTO_ADICIONAL_FRETE_OUT&in" +
                        "terfaceNamespace=http:%2F%2Fwww.brf.com%2Fhbsis%2FCUSTO_ADICIONAL_FRETE");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://spouxp2d:50201/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC" +
                        "_HB_SIS&receiverParty=&receiverService=&interface=SI_CUSTO_ADICIONAL_FRETE_OUT&i" +
                        "nterfaceNamespace=http:%2F%2Fwww.brf.com%2Fhbsis%2FCUSTO_ADICIONAL_FRETE");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
