//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_CUSTO_ADICIONAL_FRETE_OUTService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class FM_CUSTO_ADICIONAL_FRETE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao integracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao Integracao {
            get {
                return this.integracaoField;
            }
            set {
                this.integracaoField = value;
                this.RaisePropertyChanged("Integracao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroRotaField;
        
        private string[] multiTransporteField;
        
        private System.DateTime dataField;
        
        private bool dataFieldSpecified;
        
        private string placaField;
        
        private string cpfMotoristaField;
        
        private string cnpjTransportadorField;
        
        private string unidadeNegocioField;
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia[] ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumeroRota {
            get {
                return this.numeroRotaField;
            }
            set {
                this.numeroRotaField = value;
                this.RaisePropertyChanged("NumeroRota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NumeroRota", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] MultiTransporte {
            get {
                return this.multiTransporteField;
            }
            set {
                this.multiTransporteField = value;
                this.RaisePropertyChanged("MultiTransporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified {
            get {
                return this.dataFieldSpecified;
            }
            set {
                this.dataFieldSpecified = value;
                this.RaisePropertyChanged("DataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("Placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CpfMotorista {
            get {
                return this.cpfMotoristaField;
            }
            set {
                this.cpfMotoristaField = value;
                this.RaisePropertyChanged("CpfMotorista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CnpjTransportador {
            get {
                return this.cnpjTransportadorField;
            }
            set {
                this.cnpjTransportadorField = value;
                this.RaisePropertyChanged("CnpjTransportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UnidadeNegocio {
            get {
                return this.unidadeNegocioField;
            }
            set {
                this.unidadeNegocioField = value;
                this.RaisePropertyChanged("UnidadeNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ocorrencia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia[] Ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
                this.RaisePropertyChanged("Ocorrencias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string nomeField;
        
        private string quantidadeField;
        
        private string houveDivergenciaField;
        
        private string quantidadeDiariaPrevistaField;
        
        private string quantidadeDiariaRealizadaField;
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens itensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("Quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HouveDivergencia {
            get {
                return this.houveDivergenciaField;
            }
            set {
                this.houveDivergenciaField = value;
                this.RaisePropertyChanged("HouveDivergencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string QuantidadeDiariaPrevista {
            get {
                return this.quantidadeDiariaPrevistaField;
            }
            set {
                this.quantidadeDiariaPrevistaField = value;
                this.RaisePropertyChanged("QuantidadeDiariaPrevista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string QuantidadeDiariaRealizada {
            get {
                return this.quantidadeDiariaRealizadaField;
            }
            set {
                this.quantidadeDiariaRealizadaField = value;
                this.RaisePropertyChanged("QuantidadeDiariaRealizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens Itens {
            get {
                return this.itensField;
            }
            set {
                this.itensField = value;
                this.RaisePropertyChanged("Itens");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItens : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem[] itemField;
        
        private string[] nomeBalsaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NomeBalsa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] NomeBalsa {
            get {
                return this.nomeBalsaField;
            }
            set {
                this.nomeBalsaField = value;
                this.RaisePropertyChanged("NomeBalsa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE")]
    public partial class DT_CUSTO_ADICIONAL_FRETE_HBSIS_RequestIntegracaoOcorrenciaItensItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoClienteField;
        
        private string valorDescargaPrevistoField;
        
        private string valorDescargaRealizadoField;
        
        private string motivoField;
        
        private string quantidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("CodigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ValorDescargaPrevisto {
            get {
                return this.valorDescargaPrevistoField;
            }
            set {
                this.valorDescargaPrevistoField = value;
                this.RaisePropertyChanged("ValorDescargaPrevisto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ValorDescargaRealizado {
            get {
                return this.valorDescargaRealizadoField;
            }
            set {
                this.valorDescargaRealizadoField = value;
                this.RaisePropertyChanged("ValorDescargaRealizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("Quantidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", ConfigurationName="SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT")]
    public interface SI_CUSTO_ADICIONAL_FRETE_OUT {
        
        // CODEGEN: Generating message contract since the operation SI_CUSTO_ADICIONAL_FRETE_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SI_CUSTO_ADICIONAL_FRETE_OUTService.FM_CUSTO_ADICIONAL_FRETE), Action="http://sap.com/xi/WebService/soap1.1", Name="FM_CUSTO_ADICIONAL_FRETE")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse SI_CUSTO_ADICIONAL_FRETE_OUT(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", Order=0)]
        public SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTRequest() {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTRequest(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request) {
            this.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.brf.com/hbsis/CUSTO_ADICIONAL_FRETE", Order=0)]
        public SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response;
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTResponse() {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTResponse(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response) {
            this.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CUSTO_ADICIONAL_FRETE_OUTChannel : SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CUSTO_ADICIONAL_FRETE_OUTClient : System.ServiceModel.ClientBase<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT>, SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT {
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient() {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT.SI_CUSTO_ADICIONAL_FRETE_OUT(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request) {
            return base.Channel.SI_CUSTO_ADICIONAL_FRETE_OUT(request);
        }
        
        public SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Response SI_CUSTO_ADICIONAL_FRETE_OUT(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request) {
            SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest inValue = new SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest();
            inValue.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
            SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse retVal = ((SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT)(this)).SI_CUSTO_ADICIONAL_FRETE_OUT(inValue);
            return retVal.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT.SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest request) {
            return base.Channel.SI_CUSTO_ADICIONAL_FRETE_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTResponse> SI_CUSTO_ADICIONAL_FRETE_OUTAsync(SI_CUSTO_ADICIONAL_FRETE_OUTService.DT_CUSTO_ADICIONAL_FRETE_HBSIS_Request MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request) {
            SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest inValue = new SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUTRequest();
            inValue.MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request = MT_CUSTO_ADICIONAL_FRETE_HBSIS_Request;
            return ((SI_CUSTO_ADICIONAL_FRETE_OUTService.SI_CUSTO_ADICIONAL_FRETE_OUT)(this)).SI_CUSTO_ADICIONAL_FRETE_OUTAsync(inValue);
        }
    }
}
