//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBSIS.MercadoLes.Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HBSIS.Mov3rPrimaria.Services.Commons.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há anomalia de entrega pendente..
        /// </summary>
        public static string AnomaliaEntregaPendente {
            get {
                return ResourceManager.GetString("AnomaliaEntregaPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalia Inativa..
        /// </summary>
        public static string AnomaliaInativa {
            get {
                return ResourceManager.GetString("AnomaliaInativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalia já gerada no intervalo..
        /// </summary>
        public static string AnomaliaJaGerada {
            get {
                return ResourceManager.GetString("AnomaliaJaGerada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalia não encontrada..
        /// </summary>
        public static string AnomaliaNaoEncontrada {
            get {
                return ResourceManager.GetString("AnomaliaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomalia não implementada..
        /// </summary>
        public static string AnomaliaNaoImplementada {
            get {
                return ResourceManager.GetString("AnomaliaNaoImplementada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apontamento com Data conflitante..
        /// </summary>
        public static string ApontamentoConflitante {
            get {
                return ResourceManager.GetString("ApontamentoConflitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavalo não informado..
        /// </summary>
        public static string CavaloNaoInformado {
            get {
                return ResourceManager.GetString("CavaloNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca Eletrônica já existente..
        /// </summary>
        public static string CercaJaExistente {
            get {
                return ResourceManager.GetString("CercaJaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente informado não existe..
        /// </summary>
        public static string ClienteNaoExiste {
            get {
                return ResourceManager.GetString("ClienteNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não informado..
        /// </summary>
        public static string ClienteNaoInformado {
            get {
                return ResourceManager.GetString("ClienteNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string CnpjInvalido {
            get {
                return ResourceManager.GetString("CnpjInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Parada não informada..
        /// </summary>
        public static string CodParadaNaoInformado {
            get {
                return ResourceManager.GetString("CodParadaNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle de entrada e saída inválido..
        /// </summary>
        public static string ControleEntradaSaidaInvalido {
            get {
                return ResourceManager.GetString("ControleEntradaSaidaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversa não encontrada..
        /// </summary>
        public static string ConversaNaoEncontrada {
            get {
                return ResourceManager.GetString("ConversaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenada não informada..
        /// </summary>
        public static string CoordenadaNaoInformada {
            get {
                return ResourceManager.GetString("CoordenadaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início não informado..
        /// </summary>
        public static string DataInicioNaoInformado {
            get {
                return ResourceManager.GetString("DataInicioNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data maior que atual..
        /// </summary>
        public static string DataMaiorAtual {
            get {
                return ResourceManager.GetString("DataMaiorAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data menor que anterior..
        /// </summary>
        public static string DataMenorAnterior {
            get {
                return ResourceManager.GetString("DataMenorAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data não informada..
        /// </summary>
        public static string DataNaoInformada {
            get {
                return ResourceManager.GetString("DataNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Posição não informado..
        /// </summary>
        public static string DataPosicaoNaoInformada {
            get {
                return ResourceManager.GetString("DataPosicaoNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Término menor que a Data Início..
        /// </summary>
        public static string DataTerminoMenorDataInicio {
            get {
                return ResourceManager.GetString("DataTerminoMenorDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data menor que a Data Término da Parada anterior..
        /// </summary>
        public static string DataTerminoMenorParadaAnterior {
            get {
                return ResourceManager.GetString("DataTerminoMenorParadaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Término não informado..
        /// </summary>
        public static string DataTerminoNaoInformado {
            get {
                return ResourceManager.GetString("DataTerminoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parada de Entrega não vinculada ao faturamento..
        /// </summary>
        public static string EntregaNaoVinculada {
            get {
                return ResourceManager.GetString("EntregaNaoVinculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamento não encontrado..
        /// </summary>
        public static string EquipamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("EquipamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura já vinculada em outro Transporte..
        /// </summary>
        public static string FaturaJaVinculada {
            get {
                return ResourceManager.GetString("FaturaJaVinculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura não informada..
        /// </summary>
        public static string FaturaNaoInformada {
            get {
                return ResourceManager.GetString("FaturaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdMensagem não informado..
        /// </summary>
        public static string IdMensagemNaoInformado {
            get {
                return ResourceManager.GetString("IdMensagemNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude inválida..
        /// </summary>
        public static string LatitudeInvalida {
            get {
                return ResourceManager.GetString("LatitudeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude não informada..
        /// </summary>
        public static string LatitudeNaoInformada {
            get {
                return ResourceManager.GetString("LatitudeNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude inválida..
        /// </summary>
        public static string LongitudeInvalida {
            get {
                return ResourceManager.GetString("LongitudeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude não informada..
        /// </summary>
        public static string LongitudeNaoInformada {
            get {
                return ResourceManager.GetString("LongitudeNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem não informada..
        /// </summary>
        public static string MensagemNaoInformada {
            get {
                return ResourceManager.GetString("MensagemNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoramento contínuo já existente..
        /// </summary>
        public static string MonitoramentoContinuoJaExistente {
            get {
                return ResourceManager.GetString("MonitoramentoContinuoJaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo não encontrado..
        /// </summary>
        public static string MotivoNaoEncontrado {
            get {
                return ResourceManager.GetString("MotivoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo não informado..
        /// </summary>
        public static string MotivoNaoInformado {
            get {
                return ResourceManager.GetString("MotivoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorista não informado..
        /// </summary>
        public static string MotoristaNaoInformado {
            get {
                return ResourceManager.GetString("MotoristaNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não informado..
        /// </summary>
        public static string NomeNaoInformado {
            get {
                return ResourceManager.GetString("NomeNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Antena não informado..
        /// </summary>
        public static string NumeroAntenaNaoInformada {
            get {
                return ResourceManager.GetString("NumeroAntenaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número não informado..
        /// </summary>
        public static string NumeroNaoInformado {
            get {
                return ResourceManager.GetString("NumeroNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Placa inválida..
        /// </summary>
        public static string NumeroPlacaInvalida {
            get {
                return ResourceManager.GetString("NumeroPlacaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da Placa não informada..
        /// </summary>
        public static string NumeroPlacaNaoInformada {
            get {
                return ResourceManager.GetString("NumeroPlacaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta frete já vínculada a uma placa..
        /// </summary>
        public static string OfertaFreteJaVinculada {
            get {
                return ResourceManager.GetString("OfertaFreteJaVinculada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta de Frete não encontrada..
        /// </summary>
        public static string OfertaFreteNaoEncontrada {
            get {
                return ResourceManager.GetString("OfertaFreteNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação inválida..
        /// </summary>
        public static string OperacaoInvalida {
            get {
                return ResourceManager.GetString("OperacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação Transporte inválida..
        /// </summary>
        public static string OperacaoTransporteInvalida {
            get {
                return ResourceManager.GetString("OperacaoTransporteInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem informada não existe..
        /// </summary>
        public static string OrigemNaoExiste {
            get {
                return ResourceManager.GetString("OrigemNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem não informada..
        /// </summary>
        public static string OrigemNaoInformada {
            get {
                return ResourceManager.GetString("OrigemNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parada inválida..
        /// </summary>
        public static string ParadaInvalida {
            get {
                return ResourceManager.GetString("ParadaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParadaMotivo não informado..
        /// </summary>
        public static string ParadaMotivoNaoInformado {
            get {
                return ResourceManager.GetString("ParadaMotivoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parada não encontrada..
        /// </summary>
        public static string ParadaNaoEncontrada {
            get {
                return ResourceManager.GetString("ParadaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parada não informada..
        /// </summary>
        public static string ParadaNaoInformada {
            get {
                return ResourceManager.GetString("ParadaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido não informado..
        /// </summary>
        public static string PedidoNaoInformado {
            get {
                return ResourceManager.GetString("PedidoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa inválida..
        /// </summary>
        public static string PlacaInvalida {
            get {
                return ResourceManager.GetString("PlacaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacaMovimento não encontrada..
        /// </summary>
        public static string PlacaMovimentoNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaMovimentoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa não encontrada..
        /// </summary>
        public static string PlacaNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa não informada..
        /// </summary>
        public static string PlacaNaoInformada {
            get {
                return ResourceManager.GetString("PlacaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacaSinal não encontrada..
        /// </summary>
        public static string PlacaSinalNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaSinalNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacaTemperatura não encontrada..
        /// </summary>
        public static string PlacaTemperaturaNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaTemperaturaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacaTempoJornada não encontrada..
        /// </summary>
        public static string PlacaTempoJornadaNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaTempoJornadaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacaVelocidade não encontrada..
        /// </summary>
        public static string PlacaVelocidadeNaoEncontrada {
            get {
                return ResourceManager.GetString("PlacaVelocidadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polígono inválido..
        /// </summary>
        public static string PoligonoInvalido {
            get {
                return ResourceManager.GetString("PoligonoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição no passado..
        /// </summary>
        public static string PosicaoNoPassado {
            get {
                return ResourceManager.GetString("PosicaoNoPassado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raio inválido..
        /// </summary>
        public static string RaioInvalido {
            get {
                return ResourceManager.GetString("RaioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma rota possivelmente ativa para esta placa..
        /// </summary>
        public static string RotaAtiva {
            get {
                return ResourceManager.GetString("RotaAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota Finalizada..
        /// </summary>
        public static string RotaFinalizada {
            get {
                return ResourceManager.GetString("RotaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota inválida..
        /// </summary>
        public static string RotaInvalida {
            get {
                return ResourceManager.GetString("RotaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota não encontrada..
        /// </summary>
        public static string RotaNaoEncontrada {
            get {
                return ResourceManager.GetString("RotaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota não informada..
        /// </summary>
        public static string RotaNaoInformada {
            get {
                return ResourceManager.GetString("RotaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RotaParada não encontrada..
        /// </summary>
        public static string RotaParadaNaoEncontrada {
            get {
                return ResourceManager.GetString("RotaParadaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RotaParada não informada..
        /// </summary>
        public static string RotaParadaNaoInformada {
            get {
                return ResourceManager.GetString("RotaParadaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Anomalia Pendentes..
        /// </summary>
        public static string SemAnomaliaPendente {
            get {
                return ResourceManager.GetString("SemAnomaliaPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequência Repetida..
        /// </summary>
        public static string SequenciaRepetida {
            get {
                return ResourceManager.GetString("SequenciaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido..
        /// </summary>
        public static string StatusInvalido {
            get {
                return ResourceManager.GetString("StatusInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto não informado..
        /// </summary>
        public static string TextoNaoInformado {
            get {
                return ResourceManager.GetString("TextoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Anomalia não informada..
        /// </summary>
        public static string TipoAnomaliaNaoInformada {
            get {
                return ResourceManager.GetString("TipoAnomaliaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Equipamento inválido..
        /// </summary>
        public static string TipoEquipamentoInvalido {
            get {
                return ResourceManager.GetString("TipoEquipamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Equipamento não informado..
        /// </summary>
        public static string TipoEquipamentoNaoInformado {
            get {
                return ResourceManager.GetString("TipoEquipamentoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo não informado..
        /// </summary>
        public static string TipoNaoInformado {
            get {
                return ResourceManager.GetString("TipoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Parada inválido..
        /// </summary>
        public static string TipoParadaInvalido {
            get {
                return ResourceManager.GetString("TipoParadaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Parada não informada..
        /// </summary>
        public static string TipoParadaNaoInformada {
            get {
                return ResourceManager.GetString("TipoParadaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Tecnologia não informado..
        /// </summary>
        public static string TipoTecnologiaNaoInformada {
            get {
                return ResourceManager.GetString("TipoTecnologiaNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não informado..
        /// </summary>
        public static string TokenNaoInformado {
            get {
                return ResourceManager.GetString("TokenNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora não existe..
        /// </summary>
        public static string TransportadoraNaoExiste {
            get {
                return ResourceManager.GetString("TransportadoraNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora não informada..
        /// </summary>
        public static string TransportadoraNaoInfomada {
            get {
                return ResourceManager.GetString("TransportadoraNaoInfomada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte já vinculado em outra Rota..
        /// </summary>
        public static string TransporteJaVinculado {
            get {
                return ResourceManager.GetString("TransporteJaVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte não encontrado..
        /// </summary>
        public static string TransporteNaoEncontrado {
            get {
                return ResourceManager.GetString("TransporteNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte não informado..
        /// </summary>
        public static string TransporteNaoInformado {
            get {
                return ResourceManager.GetString("TransporteNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte Parada não encontrada..
        /// </summary>
        public static string TransporteParadaNaoEncontrada {
            get {
                return ResourceManager.GetString("TransporteParadaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte Parada não informado..
        /// </summary>
        public static string TransporteParadaNaoInformado {
            get {
                return ResourceManager.GetString("TransporteParadaNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratativa não implementada..
        /// </summary>
        public static string TratativaNaoImplementada {
            get {
                return ResourceManager.GetString("TratativaNaoImplementada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não encontrado..
        /// </summary>
        public static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não informado..
        /// </summary>
        public static string UsuarioNaoInformado {
            get {
                return ResourceManager.GetString("UsuarioNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválido..
        /// </summary>
        public static string UsuarioOuSenhaInvalido {
            get {
                return ResourceManager.GetString("UsuarioOuSenhaInvalido", resourceCulture);
            }
        }
    }
}
